name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ['pypy3', '3.7', '3.8', '3.9', '3.10']
        os: [macos-10.15, ubuntu-18.04, windows-2019]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools tox wheel

    - name: Build wheel
      run: python setup.py sdist bdist_wheel

    - name: Install dtcalc from wheel (for Linux and MacOS)
      if: ${{ matrix.os != 'windows-2019' }}
      run: "python -m pip install --only-binary=:all: ./dist/dtcalc-*.whl"

    - name: Install dtcalc from wheel (for Windows)
      if: ${{ matrix.os == 'windows-2019' }}
      run: "python -m pip install --only-binary=:all: --ignore-installed --find-links=dist/ dtcalc"

    # Tox fails to find PyPy on Windows. Neither "tox -e py" nor "tox -e pypy3" works.
    - name: Run tests
      if: ${{ matrix.python-version != 'pypy3' || matrix.os != 'windows-2019' }}
      run: python -m tox -e py

    - name: Check for style issues
      if: ${{ matrix.python-version == 3.7 && matrix.os == 'ubuntu-18.04' }}
      run: python -m tox -e flake8 pylint

    - name: Run mypy
      if: ${{ matrix.python-version == 3.7 && matrix.os == 'ubuntu-18.04' }}
      run: python -m tox -e mypy

    - name: Run vulture
      if: ${{ matrix.python-version == 3.7 && matrix.os == 'ubuntu-18.04' }}
      run: python -m tox -e vulture
